# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src import plagiarism_pb2 as plagiarism__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plagiarism_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlagiarismServiceStub(object):
    """Plagiarism Detection Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckPlagiarism = channel.unary_unary(
                '/plagiarism.PlagiarismService/CheckPlagiarism',
                request_serializer=plagiarism__pb2.CheckRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.UploadDocument = channel.unary_unary(
                '/plagiarism.PlagiarismService/UploadDocument',
                request_serializer=plagiarism__pb2.UploadRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.BatchUpload = channel.stream_unary(
                '/plagiarism.PlagiarismService/BatchUpload',
                request_serializer=plagiarism__pb2.UploadRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.BatchUploadResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/plagiarism.PlagiarismService/GetDocument',
                request_serializer=plagiarism__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/plagiarism.PlagiarismService/DeleteDocument',
                request_serializer=plagiarism__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.SearchDocuments = channel.unary_unary(
                '/plagiarism.PlagiarismService/SearchDocuments',
                request_serializer=plagiarism__pb2.SearchRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/plagiarism.PlagiarismService/HealthCheck',
                request_serializer=plagiarism__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.IndexPdfFromMinio = channel.unary_unary(
                '/plagiarism.PlagiarismService/IndexPdfFromMinio',
                request_serializer=plagiarism__pb2.IndexPdfFromMinioRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.IndexPdfFromMinioResponse.FromString,
                _registered_method=True)
        self.CheckPdfFromMinio = channel.unary_unary(
                '/plagiarism.PlagiarismService/CheckPdfFromMinio',
                request_serializer=plagiarism__pb2.CheckPdfFromMinioRequest.SerializeToString,
                response_deserializer=plagiarism__pb2.CheckPdfFromMinioResponse.FromString,
                _registered_method=True)


class PlagiarismServiceServicer(object):
    """Plagiarism Detection Service
    """

    def CheckPlagiarism(self, request, context):
        """Check a text for plagiarism
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDocument(self, request, context):
        """Upload a document to the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpload(self, request_iterator, context):
        """Batch upload documents (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Get document by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Delete document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocuments(self, request, context):
        """Search documents by metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexPdfFromMinio(self, request, context):
        """Index PDF from MinIO bucket - extract text, chunk with titles, and index to Elasticsearch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPdfFromMinio(self, request, context):
        """Check a PDF file from MinIO for plagiarism
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlagiarismServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckPlagiarism': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPlagiarism,
                    request_deserializer=plagiarism__pb2.CheckRequest.FromString,
                    response_serializer=plagiarism__pb2.CheckResponse.SerializeToString,
            ),
            'UploadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=plagiarism__pb2.UploadRequest.FromString,
                    response_serializer=plagiarism__pb2.UploadResponse.SerializeToString,
            ),
            'BatchUpload': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchUpload,
                    request_deserializer=plagiarism__pb2.UploadRequest.FromString,
                    response_serializer=plagiarism__pb2.BatchUploadResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=plagiarism__pb2.GetDocumentRequest.FromString,
                    response_serializer=plagiarism__pb2.GetDocumentResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=plagiarism__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=plagiarism__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=plagiarism__pb2.SearchRequest.FromString,
                    response_serializer=plagiarism__pb2.SearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=plagiarism__pb2.HealthCheckRequest.FromString,
                    response_serializer=plagiarism__pb2.HealthCheckResponse.SerializeToString,
            ),
            'IndexPdfFromMinio': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexPdfFromMinio,
                    request_deserializer=plagiarism__pb2.IndexPdfFromMinioRequest.FromString,
                    response_serializer=plagiarism__pb2.IndexPdfFromMinioResponse.SerializeToString,
            ),
            'CheckPdfFromMinio': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPdfFromMinio,
                    request_deserializer=plagiarism__pb2.CheckPdfFromMinioRequest.FromString,
                    response_serializer=plagiarism__pb2.CheckPdfFromMinioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plagiarism.PlagiarismService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plagiarism.PlagiarismService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlagiarismService(object):
    """Plagiarism Detection Service
    """

    @staticmethod
    def CheckPlagiarism(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plagiarism.PlagiarismService/CheckPlagiarism',
            plagiarism__pb2.CheckRequest.SerializeToString,
            plagiarism__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plagiarism.PlagiarismService/UploadDocument',
            plagiarism__pb2.UploadRequest.SerializeToString,
            plagiarism__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/plagiarism.PlagiarismService/BatchUpload',
            plagiarism__pb2.UploadRequest.SerializeToString,
            plagiarism__pb2.BatchUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plagiarism.PlagiarismService/GetDocument',
            plagiarism__pb2.GetDocumentRequest.SerializeToString,
            plagiarism__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plagiarism.PlagiarismService/DeleteDocument',
            plagiarism__pb2.DeleteDocumentRequest.SerializeToString,
            plagiarism__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plagiarism.PlagiarismService/SearchDocuments',
            plagiarism__pb2.SearchRequest.SerializeToString,
            plagiarism__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plagiarism.PlagiarismService/HealthCheck',
            plagiarism__pb2.HealthCheckRequest.SerializeToString,
            plagiarism__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexPdfFromMinio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plagiarism.PlagiarismService/IndexPdfFromMinio',
            plagiarism__pb2.IndexPdfFromMinioRequest.SerializeToString,
            plagiarism__pb2.IndexPdfFromMinioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPdfFromMinio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plagiarism.PlagiarismService/CheckPdfFromMinio',
            plagiarism__pb2.CheckPdfFromMinioRequest.SerializeToString,
            plagiarism__pb2.CheckPdfFromMinioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
